LIBRARY := SUHH2common
DICT :=  include/ReconstructionHypothesis.h include/SUHH2common_LinkDef.h
#USERCXXFLAGS := -I/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/lhapdf/6.1.6-ikhhed/include/
USERCXXFLAGS := -I/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/lhapdf/6.2.1/include/
TEST := 1
USERLDFLAGS := -lSUHH2core -lSUHH2JetMETObjects -lMinuit -lGenVector -L/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/lhapdf/6.2.1/lib -lLHAPDF
include ../Makefile.common
